"""
DanDan专用工具模块
"""

from .constants import (
    DANDAN_TYPE_MAPPING,
    DANDAN_TYPE_DESC_MAPPING,
    FALLBACK_SEARCH_BANGUMI_ID,
    EPISODE_MAPPING_CACHE_PREFIX,
    FALLBACK_SEARCH_CACHE_PREFIX,
    TOKEN_SEARCH_TASKS_PREFIX,
    USER_LAST_BANGUMI_CHOICE_PREFIX,
    COMMENTS_FETCH_CACHE_PREFIX,
    SAMPLED_COMMENTS_CACHE_PREFIX,
    FALLBACK_SEARCH_CACHE_TTL,
    TOKEN_SEARCH_TASKS_TTL,
    USER_LAST_BANGUMI_CHOICE_TTL,
    COMMENTS_FETCH_CACHE_TTL,
    SAMPLED_COMMENTS_CACHE_TTL_DB,
)

from .serialization import convert_to_serializable, fix_bangumi_mapping

__all__ = [
    # 常量
    'DANDAN_TYPE_MAPPING',
    'DANDAN_TYPE_DESC_MAPPING',
    'FALLBACK_SEARCH_BANGUMI_ID',
    'EPISODE_MAPPING_CACHE_PREFIX',
    'FALLBACK_SEARCH_CACHE_PREFIX',
    'TOKEN_SEARCH_TASKS_PREFIX',
    'USER_LAST_BANGUMI_CHOICE_PREFIX',
    'COMMENTS_FETCH_CACHE_PREFIX',
    'SAMPLED_COMMENTS_CACHE_PREFIX',
    'FALLBACK_SEARCH_CACHE_TTL',
    'TOKEN_SEARCH_TASKS_TTL',
    'USER_LAST_BANGUMI_CHOICE_TTL',
    'COMMENTS_FETCH_CACHE_TTL',
    'SAMPLED_COMMENTS_CACHE_TTL_DB',
    # 工具函数
    'convert_to_serializable',
    'fix_bangumi_mapping',
]
